<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="13" ignored="0" total="32" passed="19">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="4387" started-at="2019-09-08T20:42:18Z" finished-at="2019-09-08T20:42:23Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="4387" started-at="2019-09-08T20:42:18Z" finished-at="2019-09-08T20:42:23Z">
      <class name="postAPITests.SpotTradeTests">
        <test-method status="PASS" signature="setup()[pri:0, instance:postAPITests.SpotTradeTests@ae45eb6]" name="setup" is-config="true" duration-ms="1" started-at="2019-09-08T20:42:19Z" description="Setup API request" finished-at="2019-09-08T20:42:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="tc010_spot_invalid_value_date()[pri:0, instance:postAPITests.SpotTradeTests@ae45eb6]" name="tc010_spot_invalid_value_date" duration-ms="1764" started-at="2019-09-08T20:42:19Z" description="SPOT:Invalid Value date should throw an error" finished-at="2019-09-08T20:42:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.SpotTradeTests.validate(SpotTradeTests.java:148)
at postAPITests.SpotTradeTests.tc010_spot_invalid_value_date(SpotTradeTests.java:135)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc010_spot_invalid_value_date -->
        <test-method status="PASS" signature="tc01_spot_value_date_after_trade_date()[pri:0, instance:postAPITests.SpotTradeTests@ae45eb6]" name="tc01_spot_value_date_after_trade_date" duration-ms="112" started-at="2019-09-08T20:42:21Z" description="SPOT:Value date is after trade date, with valid counterparty, legal entity and currency" finished-at="2019-09-08T20:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc01_spot_value_date_after_trade_date -->
        <test-method status="PASS" signature="tc02_spot_value_date_same_as_trade_date()[pri:0, instance:postAPITests.SpotTradeTests@ae45eb6]" name="tc02_spot_value_date_same_as_trade_date" duration-ms="58" started-at="2019-09-08T20:42:21Z" description="SPOT:Value date is same as trade date" finished-at="2019-09-08T20:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc02_spot_value_date_same_as_trade_date -->
        <test-method status="PASS" signature="tc03_spot_value_date_before_trade_date()[pri:0, instance:postAPITests.SpotTradeTests@ae45eb6]" name="tc03_spot_value_date_before_trade_date" duration-ms="56" started-at="2019-09-08T20:42:21Z" description="SPOT:Value date is before trade date" finished-at="2019-09-08T20:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc03_spot_value_date_before_trade_date -->
        <test-method status="PASS" signature="tc04_spot_check_supported_counterparty()[pri:0, instance:postAPITests.SpotTradeTests@ae45eb6]" name="tc04_spot_check_supported_counterparty" duration-ms="45" started-at="2019-09-08T20:42:21Z" description="SPOT:Check supported counterparty" finished-at="2019-09-08T20:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc04_spot_check_supported_counterparty -->
        <test-method status="PASS" signature="tc05_spot_unsupported_counterparty()[pri:0, instance:postAPITests.SpotTradeTests@ae45eb6]" name="tc05_spot_unsupported_counterparty" duration-ms="62" started-at="2019-09-08T20:42:21Z" description="SPOT:Unsupported counterparty should throw an error" finished-at="2019-09-08T20:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc05_spot_unsupported_counterparty -->
        <test-method status="FAIL" signature="tc06_spot_illegal_entity()[pri:0, instance:postAPITests.SpotTradeTests@ae45eb6]" name="tc06_spot_illegal_entity" duration-ms="54" started-at="2019-09-08T20:42:21Z" description="SPOT:Using an illegal entity should throw an error" finished-at="2019-09-08T20:42:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.SpotTradeTests.validate(SpotTradeTests.java:148)
at postAPITests.SpotTradeTests.tc06_spot_illegal_entity(SpotTradeTests.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc06_spot_illegal_entity -->
        <test-method status="PASS" signature="tc07_spot_invalid_currency()[pri:0, instance:postAPITests.SpotTradeTests@ae45eb6]" name="tc07_spot_invalid_currency" duration-ms="56" started-at="2019-09-08T20:42:21Z" description="SPOT:Invalid currencies should throw an error" finished-at="2019-09-08T20:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc07_spot_invalid_currency -->
        <test-method status="PASS" signature="tc08_spot_weekend_value_date()[pri:0, instance:postAPITests.SpotTradeTests@ae45eb6]" name="tc08_spot_weekend_value_date" duration-ms="48" started-at="2019-09-08T20:42:21Z" description="SPOT:Value date on weekends should throw an error" finished-at="2019-09-08T20:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc08_spot_weekend_value_date -->
        <test-method status="FAIL" signature="tc09_spot_value_date_currency_non_working_day()[pri:0, instance:postAPITests.SpotTradeTests@ae45eb6]" name="tc09_spot_value_date_currency_non_working_day" duration-ms="43" started-at="2019-09-08T20:42:21Z" description="SPOT:Value date on currency non-working day should throw an error" finished-at="2019-09-08T20:42:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.SpotTradeTests.validate(SpotTradeTests.java:148)
at postAPITests.SpotTradeTests.tc09_spot_value_date_currency_non_working_day(SpotTradeTests.java:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc09_spot_value_date_currency_non_working_day -->
      </class> <!-- postAPITests.SpotTradeTests -->
      <class name="postAPITests.BatchValidation">
        <test-method status="PASS" signature="setup()[pri:0, instance:postAPITests.BatchValidation@59f99ea]" name="setup" is-config="true" duration-ms="1" started-at="2019-09-08T20:42:22Z" description="Setup API request" finished-at="2019-09-08T20:42:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="TC01_batch_request()[pri:0, instance:postAPITests.BatchValidation@59f99ea]" name="TC01_batch_request" duration-ms="129" started-at="2019-09-08T20:42:22Z" description="Run batch request" finished-at="2019-09-08T20:42:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Status mismatch ovserved for TC --> tc06_spot_illegal_entity expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc06_spot_illegal_entity expected [true] but found [false],
Status mismatch ovserved for TC --> tc09_spot_value_date_currency_non_working_day expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc09_spot_value_date_currency_non_working_day expected [true] but found [false],
Status mismatch ovserved for TC --> tc010_spot_invalid_value_date expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc010_spot_invalid_value_date expected [true] but found [false],
Status mismatch ovserved for TC --> tc15_forward_value_date_currency_non_working_day expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc15_forward_value_date_currency_non_working_day expected [true] but found [false],
Status mismatch ovserved for TC --> tc16_invalid_value_date expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc16_invalid_value_date expected [true] but found [false],
Status mismatch ovserved for TC --> tc18_options_american_excerciseStartDate_before_tradeDate_and_expiryDate expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc18_options_american_excerciseStartDate_before_tradeDate_and_expiryDate expected [true] but found [false],
Status mismatch ovserved for TC --> tc19_options_american_excerciseStartDate_after_tradeDate_and_expiryDate expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc19_options_american_excerciseStartDate_after_tradeDate_and_expiryDate expected [true] but found [false],
Message mismatch observed for TC --> tc20_options_american_deliveryDate_before_premiumDate expected [true] but found [false],
Status mismatch ovserved for TC --> tc24_options_american_missing_excerciseStartDate expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc24_options_american_missing_excerciseStartDate expected [true] but found [false],
Status mismatch ovserved for TC --> tc25_options_american_invalid_tradeDate expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc25_options_american_invalid_tradeDate expected [true] but found [false],
Message mismatch observed for TC --> tc28_options_european_premiumDate_same_as_deliveryDate expected [true] but found [false],
Status mismatch ovserved for TC --> tc31_options_european_invalid_deliveryDate expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc31_options_european_invalid_deliveryDate expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Status mismatch ovserved for TC --> tc06_spot_illegal_entity expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc06_spot_illegal_entity expected [true] but found [false],
Status mismatch ovserved for TC --> tc09_spot_value_date_currency_non_working_day expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc09_spot_value_date_currency_non_working_day expected [true] but found [false],
Status mismatch ovserved for TC --> tc010_spot_invalid_value_date expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc010_spot_invalid_value_date expected [true] but found [false],
Status mismatch ovserved for TC --> tc15_forward_value_date_currency_non_working_day expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc15_forward_value_date_currency_non_working_day expected [true] but found [false],
Status mismatch ovserved for TC --> tc16_invalid_value_date expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc16_invalid_value_date expected [true] but found [false],
Status mismatch ovserved for TC --> tc18_options_american_excerciseStartDate_before_tradeDate_and_expiryDate expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc18_options_american_excerciseStartDate_before_tradeDate_and_expiryDate expected [true] but found [false],
Status mismatch ovserved for TC --> tc19_options_american_excerciseStartDate_after_tradeDate_and_expiryDate expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc19_options_american_excerciseStartDate_after_tradeDate_and_expiryDate expected [true] but found [false],
Message mismatch observed for TC --> tc20_options_american_deliveryDate_before_premiumDate expected [true] but found [false],
Status mismatch ovserved for TC --> tc24_options_american_missing_excerciseStartDate expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc24_options_american_missing_excerciseStartDate expected [true] but found [false],
Status mismatch ovserved for TC --> tc25_options_american_invalid_tradeDate expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc25_options_american_invalid_tradeDate expected [true] but found [false],
Message mismatch observed for TC --> tc28_options_european_premiumDate_same_as_deliveryDate expected [true] but found [false],
Status mismatch ovserved for TC --> tc31_options_european_invalid_deliveryDate expected [ERROR] but found [SUCCESS],
Message mismatch observed for TC --> tc31_options_european_invalid_deliveryDate expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.BatchValidation.validate(BatchValidation.java:56)
at postAPITests.BatchValidation.TC01_batch_request(BatchValidation.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_batch_request -->
      </class> <!-- postAPITests.BatchValidation -->
      <class name="postAPITests.ForwardTradeTests">
        <test-method status="PASS" signature="setup()[pri:0, instance:postAPITests.ForwardTradeTests@3532ec19]" name="setup" is-config="true" duration-ms="539" started-at="2019-09-08T20:42:18Z" description="Setup API request" finished-at="2019-09-08T20:42:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="setup()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="setup" is-config="true" duration-ms="1" started-at="2019-09-08T20:42:19Z" description="Setup API request" finished-at="2019-09-08T20:42:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="tc11_forward_value_date_after_trade_date()[pri:0, instance:postAPITests.ForwardTradeTests@3532ec19]" name="tc11_forward_value_date_after_trade_date" duration-ms="51" started-at="2019-09-08T20:42:21Z" description="FORWARD:Value date is after trade date, with valid counterparty, legal entity and currency" finished-at="2019-09-08T20:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc11_forward_value_date_after_trade_date -->
        <test-method status="PASS" signature="tc12_forward_value_date_same_as_trade_date()[pri:0, instance:postAPITests.ForwardTradeTests@3532ec19]" name="tc12_forward_value_date_same_as_trade_date" duration-ms="50" started-at="2019-09-08T20:42:21Z" description="FORWARD:Value date is same as trade date" finished-at="2019-09-08T20:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc12_forward_value_date_same_as_trade_date -->
        <test-method status="PASS" signature="tc13_forward_value_date_before_trade_date()[pri:0, instance:postAPITests.ForwardTradeTests@3532ec19]" name="tc13_forward_value_date_before_trade_date" duration-ms="60" started-at="2019-09-08T20:42:21Z" description="FORWARD:Value date is before trade date" finished-at="2019-09-08T20:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc13_forward_value_date_before_trade_date -->
        <test-method status="PASS" signature="tc14_forward_weekend_value_date()[pri:0, instance:postAPITests.ForwardTradeTests@3532ec19]" name="tc14_forward_weekend_value_date" duration-ms="48" started-at="2019-09-08T20:42:21Z" description="FORWARD:Value date on weekends should throw an error" finished-at="2019-09-08T20:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc14_forward_weekend_value_date -->
        <test-method status="FAIL" signature="tc15_forward_value_date_currency_non_working_day()[pri:0, instance:postAPITests.ForwardTradeTests@3532ec19]" name="tc15_forward_value_date_currency_non_working_day" duration-ms="43" started-at="2019-09-08T20:42:21Z" description="FORWARD:Value date on currency non-working day should throw an error" finished-at="2019-09-08T20:42:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.ForwardTradeTests.validate(ForwardTradeTests.java:104)
at postAPITests.ForwardTradeTests.tc15_forward_value_date_currency_non_working_day(ForwardTradeTests.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc15_forward_value_date_currency_non_working_day -->
        <test-method status="FAIL" signature="tc16_invalid_value_date()[pri:0, instance:postAPITests.ForwardTradeTests@3532ec19]" name="tc16_invalid_value_date" duration-ms="67" started-at="2019-09-08T20:42:21Z" description="FORWARD:Invalid value date should throw an error" finished-at="2019-09-08T20:42:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.ForwardTradeTests.validate(ForwardTradeTests.java:104)
at postAPITests.ForwardTradeTests.tc16_invalid_value_date(ForwardTradeTests.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc16_invalid_value_date -->
      </class> <!-- postAPITests.ForwardTradeTests -->
      <class name="postAPITests.OptionTradeTests">
        <test-method status="PASS" signature="tc17_options_american_exerciseStartDate_after_tradeDate_before_expiryDate()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="tc17_options_american_exerciseStartDate_after_tradeDate_before_expiryDate" duration-ms="78" started-at="2019-09-08T20:42:21Z" description="OPTIONS:For American style, exerciseStartDate is after trade date but before the expiry date" finished-at="2019-09-08T20:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc17_options_american_exerciseStartDate_after_tradeDate_before_expiryDate -->
        <test-method status="FAIL" signature="tc18_options_american_excerciseStartDate_before_tradeDate_and_expiryDate()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="tc18_options_american_excerciseStartDate_before_tradeDate_and_expiryDate" duration-ms="230" started-at="2019-09-08T20:42:21Z" description="OPTIONS:For American style, exerciseStartDate before trade date &amp; expiry date should throw error" finished-at="2019-09-08T20:42:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.OptionTradeTests.validate(OptionTradeTests.java:204)
at postAPITests.OptionTradeTests.tc18_options_american_excerciseStartDate_before_tradeDate_and_expiryDate(OptionTradeTests.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc18_options_american_excerciseStartDate_before_tradeDate_and_expiryDate -->
        <test-method status="FAIL" signature="tc19_options_american_excerciseStartDate_after_tradeDate_and_expiryDate()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="tc19_options_american_excerciseStartDate_after_tradeDate_and_expiryDate" duration-ms="54" started-at="2019-09-08T20:42:22Z" description="OPTIONS:For American style, exerciseStartDate after trade date &amp; expiry date should throw error" finished-at="2019-09-08T20:42:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.OptionTradeTests.validate(OptionTradeTests.java:204)
at postAPITests.OptionTradeTests.tc19_options_american_excerciseStartDate_after_tradeDate_and_expiryDate(OptionTradeTests.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc19_options_american_excerciseStartDate_after_tradeDate_and_expiryDate -->
        <test-method status="FAIL" signature="tc20_options_american_deliveryDate_before_premiumDate()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="tc20_options_american_deliveryDate_before_premiumDate" duration-ms="57" started-at="2019-09-08T20:42:22Z" description="OPTIONS:For American style, deliveryDate before premiumDate should throw error" finished-at="2019-09-08T20:42:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Expected and actual Post response messages doesn't match expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actual Post response messages doesn't match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.OptionTradeTests.validate(OptionTradeTests.java:204)
at postAPITests.OptionTradeTests.tc20_options_american_deliveryDate_before_premiumDate(OptionTradeTests.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc20_options_american_deliveryDate_before_premiumDate -->
        <test-method status="PASS" signature="tc21_options_american_expiryDate_on_weekend()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="tc21_options_american_expiryDate_on_weekend" duration-ms="49" started-at="2019-09-08T20:42:22Z" description="OPTIONS:For American style, expiryDate on weekend should throw error" finished-at="2019-09-08T20:42:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc21_options_american_expiryDate_on_weekend -->
        <test-method status="PASS" signature="tc22_options_american_expiryDate_before_tradeDate()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="tc22_options_american_expiryDate_before_tradeDate" duration-ms="41" started-at="2019-09-08T20:42:22Z" description="OPTIONS:For American style, expiryDate before tradeDate should throw error" finished-at="2019-09-08T20:42:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc22_options_american_expiryDate_before_tradeDate -->
        <test-method status="PASS" signature="tc23_options_american_expiryDate_after_deliveryDate()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="tc23_options_american_expiryDate_after_deliveryDate" duration-ms="51" started-at="2019-09-08T20:42:22Z" description="OPTIONS:For American style, expiryDate after deliveryDate should throw error" finished-at="2019-09-08T20:42:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc23_options_american_expiryDate_after_deliveryDate -->
        <test-method status="FAIL" signature="tc24_options_american_missing_excerciseStartDate()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="tc24_options_american_missing_excerciseStartDate" duration-ms="55" started-at="2019-09-08T20:42:22Z" description="OPTIONS:For American style, missing exerciseStartDate should throw error" finished-at="2019-09-08T20:42:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.OptionTradeTests.validate(OptionTradeTests.java:204)
at postAPITests.OptionTradeTests.tc24_options_american_missing_excerciseStartDate(OptionTradeTests.java:112)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc24_options_american_missing_excerciseStartDate -->
        <test-method status="FAIL" signature="tc25_options_american_invalid_tradeDate()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="tc25_options_american_invalid_tradeDate" duration-ms="43" started-at="2019-09-08T20:42:22Z" description="OPTIONS:For American style, invalid tradeDate should throw error" finished-at="2019-09-08T20:42:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.OptionTradeTests.validate(OptionTradeTests.java:204)
at postAPITests.OptionTradeTests.tc25_options_american_invalid_tradeDate(OptionTradeTests.java:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc25_options_american_invalid_tradeDate -->
        <test-method status="PASS" signature="tc26_options_european_expiryDate_premiumDate_before_deliveryDate()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="tc26_options_european_expiryDate_premiumDate_before_deliveryDate" duration-ms="53" started-at="2019-09-08T20:42:22Z" description="OPTIONS:For European style, expiryDate &amp; premiumDate should be before deliveryDate" finished-at="2019-09-08T20:42:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc26_options_european_expiryDate_premiumDate_before_deliveryDate -->
        <test-method status="PASS" signature="tc27_options_invalid_style()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="tc27_options_invalid_style" duration-ms="47" started-at="2019-09-08T20:42:22Z" description="OPTIONS:For invalid style, API should throw error" finished-at="2019-09-08T20:42:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc27_options_invalid_style -->
        <test-method status="FAIL" signature="tc28_options_european_premiumDate_same_as_deliveryDate()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="tc28_options_european_premiumDate_same_as_deliveryDate" duration-ms="60" started-at="2019-09-08T20:42:22Z" description="OPTIONS:For European style, when premiumDate &amp; deliveryDate is same, API should throw error" finished-at="2019-09-08T20:42:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Expected and actual Post response messages doesn't match expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actual Post response messages doesn't match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.OptionTradeTests.validate(OptionTradeTests.java:204)
at postAPITests.OptionTradeTests.tc28_options_european_premiumDate_same_as_deliveryDate(OptionTradeTests.java:157)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc28_options_european_premiumDate_same_as_deliveryDate -->
        <test-method status="PASS" signature="tc29_options_european_expiryDate_after_premiumDate_before_deliveryDate()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="tc29_options_european_expiryDate_after_premiumDate_before_deliveryDate" duration-ms="40" started-at="2019-09-08T20:42:22Z" description="OPTIONS:For European style, expiryDate is after premiumDate but before deliveryDate" finished-at="2019-09-08T20:42:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc29_options_european_expiryDate_after_premiumDate_before_deliveryDate -->
        <test-method status="PASS" signature="tc30_options_european_expiryDate_premiumDate_after_deliveryDate()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="tc30_options_european_expiryDate_premiumDate_after_deliveryDate" duration-ms="105" started-at="2019-09-08T20:42:22Z" description="OPTIONS:For European style, expiryDate &amp; premiumDate is after deliveryDate" finished-at="2019-09-08T20:42:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc30_options_european_expiryDate_premiumDate_after_deliveryDate -->
        <test-method status="FAIL" signature="tc31_options_european_invalid_deliveryDate()[pri:0, instance:postAPITests.OptionTradeTests@68c4039c]" name="tc31_options_european_invalid_deliveryDate" duration-ms="41" started-at="2019-09-08T20:42:22Z" description="OPTIONS:For European style, invalid deliveryDate should throw error" finished-at="2019-09-08T20:42:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.OptionTradeTests.validate(OptionTradeTests.java:204)
at postAPITests.OptionTradeTests.tc31_options_european_invalid_deliveryDate(OptionTradeTests.java:191)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc31_options_european_invalid_deliveryDate -->
      </class> <!-- postAPITests.OptionTradeTests -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
